# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydict',
            name='desc',
        ),
    ]
