# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影院名')),
                ('Cinema_id', models.IntegerField(default=0, verbose_name='电影院id')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影院',
                'verbose_name_plural': '电影院',
            },
        ),
        migrations.CreateModel(
            name='CinemaMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('cinema_name', models.CharField(max_length=50, verbose_name='电影院名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影与电影院绑定',
                'verbose_name_plural': '电影与电影院绑定',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CorD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='区县名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('cord_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.City', verbose_name='城市外键')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影名')),
                ('doubanid', models.IntegerField(default=0, verbose_name='豆瓣电影id')),
                ('movie_score', models.CharField(max_length=10, verbose_name='电影评分')),
                ('movie_image', models.ImageField(default='static/image/movie/default.png', upload_to='static/image/movie/%Y/%m', verbose_name='图片')),
                ('movie_time', models.CharField(default='', max_length=50, verbose_name='片长')),
                ('movie_info', models.CharField(default='', max_length=1000, verbose_name='电影详情1')),
                ('movie_info1', models.CharField(default='', max_length=1000, verbose_name='电影详情2')),
                ('movie_detail', models.CharField(default='', max_length=500, verbose_name='电影内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(default='', max_length=20, verbose_name='豆瓣用户名')),
                ('comment_time', models.CharField(default='', max_length=100, verbose_name='豆瓣评论时间')),
                ('comment_degree', models.CharField(default='', max_length=20, verbose_name='推荐等级')),
                ('comment_like_nums', models.IntegerField(default=0, verbose_name='有用数量')),
                ('movie_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('doubanid', models.IntegerField(default=0, verbose_name='豆瓣电影id')),
                ('comment', models.CharField(max_length=200, verbose_name='电影评论')),
                ('comment_type', models.CharField(choices=[('1', '豆瓣'), ('2', '用户')], default='豆瓣', max_length=6, verbose_name='评论类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影评论',
                'verbose_name_plural': '电影评论',
            },
        ),
        migrations.CreateModel(
            name='MovieTicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField(default=0, verbose_name='票价')),
                ('ticket_url', models.CharField(default='', max_length=200, verbose_name='url')),
                ('ticket_time', models.DateField(blank=True, null=True, verbose_name='票日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('ticket_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='电影外键')),
            ],
            options={
                'verbose_name': '电影票信息',
                'verbose_name_plural': '电影票信息',
            },
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_cord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.CorD', verbose_name='区县外键'),
        ),
    ]
