# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_emotion_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fav_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
