# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_fav_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='emotion_num',
            field=models.FloatField(default=0, verbose_name='情感分析数值'),
        ),
    ]
