# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20180331_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieticketinfo',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='movieticketinfo',
            name='ticket_time',
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_e_time',
            field=models.CharField(default='', max_length=50, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_lg',
            field=models.CharField(default='', max_length=50, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_np',
            field=models.CharField(default='', max_length=50, verbose_name='新价格'),
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_op',
            field=models.CharField(default='', max_length=50, verbose_name='旧价格'),
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_s_time',
            field=models.CharField(default='', max_length=50, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='movieticketinfo',
            name='ticket_tn',
            field=models.CharField(default='', max_length=50, verbose_name='厅'),
        ),
    ]
