# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rmovieticketinfo_ticket_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieticketinfo',
            name='ticket_url',
        ),
        migrations.RemoveField(
            model_name='rmovieticketinfo',
            name='ticket_movie',
        ),
        migrations.RemoveField(
            model_name='rmovieticketinfo',
            name='ticket_url',
        ),
    ]
