# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20180331_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmovieticketinfo',
            name='ticket_type',
        ),
    ]
