# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_rmovieticketinfo_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmovieticketinfo',
            name='ticket_type',
            field=models.CharField(default='', max_length=50, verbose_name='类型'),
        ),
    ]
