# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='房名')),
                ('house_price', models.IntegerField(default=0, verbose_name='价格')),
                ('house_detail', models.CharField(default='', max_length=50, verbose_name='信息')),
                ('house_image', models.ImageField(default='static/image/house/default.png', upload_to='static/image/house/%Y/%m', verbose_name='图片')),
                ('house_image_url', models.CharField(max_length=200, verbose_name='图片url')),
                ('house_url', models.CharField(default='', max_length=200, verbose_name='url')),
                ('house_address', models.CharField(max_length=50, verbose_name='地址')),
                ('house_type', models.CharField(choices=[('1', '58同城'), ('2', 'anjuke'), ('3', 'fangtianxia')], default='58同城', max_length=6, verbose_name='类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('house_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.City', verbose_name='城市外键')),
            ],
            options={
                'verbose_name': '房源信息',
                'verbose_name_plural': '房源信息',
            },
        ),
    ]
